package modelo;
// Generated 6 dic 2025, 18:14:20 by Hibernate Tools 6.5.1.Final

/**
 * CentrosMeteorologicos generated by hbm2java
 */
public class CentrosMeteorologicos implements java.io.Serializable {

	private Integer idCentroMet;
	private String nombre;
	private Integer idMunicipio;
	private String direccion;
	private Double latitud;
	private Double longitud;
	private String url;
	private String hash;

	public CentrosMeteorologicos() {
	}

	public CentrosMeteorologicos(String nombre, Integer idMunicipio, String direccion, Double latitud, Double longitud,
			String url, String hash) {
		this.nombre = nombre;
		this.idMunicipio = idMunicipio;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.url = url;
		this.hash = hash;
	}

	public Integer getIdCentroMet() {
		return this.idCentroMet;
	}

	public void setIdCentroMet(Integer idCentroMet) {
		this.idCentroMet = idCentroMet;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
