package modelo;
// Generated 6 dic 2025, 18:14:20 by Hibernate Tools 6.5.1.Final

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private Integer idEspacio;
	private String nombre;
	private String descripcion;
	private String tipo;
	private String categoria;
	private Double latitud;
	private Double longitud;

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(String nombre, String descripcion, String tipo, String categoria, Double latitud,
			Double longitud) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.categoria = categoria;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public Integer getIdEspacio() {
		return this.idEspacio;
	}

	public void setIdEspacio(Integer idEspacio) {
		this.idEspacio = idEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

}
