package modelo;
// Generated 6 dic 2025, 18:14:20 by Hibernate Tools 6.5.1.Final

/**
 * MunicipiosEspaciosNat generated by hbm2java
 */
public class MunicipiosEspaciosNat implements java.io.Serializable {

	private MunicipiosEspaciosNatId id;

	public MunicipiosEspaciosNat() {
	}

	public MunicipiosEspaciosNat(MunicipiosEspaciosNatId id) {
		this.id = id;
	}

	public MunicipiosEspaciosNatId getId() {
		return this.id;
	}

	public void setId(MunicipiosEspaciosNatId id) {
		this.id = id;
	}

}
