package modelo;
// Generated 6 dic 2025, 18:14:20 by Hibernate Tools 6.5.1.Final

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private int idMunicipio;
	private String nombre;
	private String descripcion;
	private Integer codMunicipio;
	private Integer idProvincia;

	public Municipios() {
	}

	public Municipios(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Municipios(int idMunicipio, String nombre, String descripcion, Integer codMunicipio, Integer idProvincia) {
		this.idMunicipio = idMunicipio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codMunicipio = codMunicipio;
		this.idProvincia = idProvincia;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

}
