package modelo;
// Generated 6 dic 2025, 18:14:20 by Hibernate Tools 6.5.1.Final

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int idProvincia;
	private String nombre;

	public Provincias() {
	}

	public Provincias(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Provincias(int idProvincia, String nombre) {
		this.idProvincia = idProvincia;
		this.nombre = nombre;
	}

	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
