package modelo;
// Generated 1 dic 2025, 10:51:02 by Hibernate Tools 6.5.1.Final

/**
 * MunicipiosEspaciosNat generated by hbm2java
 */
public class MunicipiosEspaciosNat implements java.io.Serializable {

	private MunicipiosEspaciosNatId id;
	private Municipios municipios;
	private EspaciosNaturales espaciosNaturales;

	public MunicipiosEspaciosNat() {
	}

	public MunicipiosEspaciosNat(MunicipiosEspaciosNatId id, Municipios municipios,
			EspaciosNaturales espaciosNaturales) {
		this.id = id;
		this.municipios = municipios;
		this.espaciosNaturales = espaciosNaturales;
	}

	public MunicipiosEspaciosNatId getId() {
		return this.id;
	}

	public void setId(MunicipiosEspaciosNatId id) {
		this.id = id;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public EspaciosNaturales getEspaciosNaturales() {
		return this.espaciosNaturales;
	}

	public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
		this.espaciosNaturales = espaciosNaturales;
	}

}
